server:
  port: 8082

spring:
  profiles:
    active: local
  mail:
    host: smtp-relay.brevo.com
    port: 2525
    username: michal.m.szczepanski@gmail.com
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true