spring:
  kafka:
    bootstrap-servers: localhost:9092

logging:
  level:
    org.flywaydb: TRACE
    org.hibernate.SQL: TRACE
    org.apache:
      kafka:
        clients:
          producer:
            internals: TRACE